# Generated by Django 3.1.6 on 2021-02-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.TextField(default='https://avatars.githubusercontent.com/u/78534587?s=200&v=4'),
        ),
    ]
