# Generated by Django 3.1.6 on 2021-02-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210205_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.ManyToManyField(to='users.Badge'),
        ),
    ]
