# Generated by Django 3.1.6 on 2021-02-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='friend', through='users.UserFriend', to='users.Profile'),
        ),
    ]
