# Generated by Django 3.1.6 on 2021-02-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210206_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(through='users.UserFriend', to='users.Profile'),
        ),
    ]
