# Generated by Django 3.1.6 on 2021-02-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210206_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='_profile_friends_+', through='users.UserFriend', to='users.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='userfriend',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userfriend',
            name='source',
        ),
        migrations.RemoveField(
            model_name='userfriend',
            name='target',
        ),
    ]
