# Generated by Django 3.1.6 on 2021-02-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_code',
            field=models.CharField(max_length=20),
        ),
    ]
